config/routes.rb
Rails.application.routes.draw do
  resources :collectibles
  resources :collections
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collectible.rb
class Collectible < ApplicationRecord
  belongs_to :collection
end

app/models/collection.rb
class Collection < ApplicationRecord
	has_many :collectibles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/collectibles_controller.rb
class CollectiblesController < ApplicationController
  before_action :set_collectible, only: [:show, :edit, :update, :destroy]

  # GET /collectibles
  # GET /collectibles.json
  def index
    @collectibles = Collectible.all
  end

  # GET /collectibles/1
  # GET /collectibles/1.json
  def show
  end

  # GET /collectibles/new
  def new
    @collectible = Collectible.new
  end

  # GET /collectibles/1/edit
  def edit
  end

  # POST /collectibles
  # POST /collectibles.json
  def create
	p collectible_params
    @collectible = Collectible.new(collectible_params)

    respond_to do |format|
      if @collectible.save
        format.html { redirect_to @collectible, notice: 'Collectible was successfully created.' }
        format.json { render :show, status: :created, location: @collectible }
      else
        format.html { render :new }
        format.json { render json: @collectible.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collectibles/1
  # PATCH/PUT /collectibles/1.json
  def update
    respond_to do |format|
      if @collectible.update(collectible_params)
        format.html { redirect_to @collectible, notice: 'Collectible was successfully updated.' }
        format.json { render :show, status: :ok, location: @collectible }
      else
        format.html { render :edit }
        format.json { render json: @collectible.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collectibles/1
  # DELETE /collectibles/1.json
  def destroy
    @collectible.destroy
    respond_to do |format|
      format.html { redirect_to collectibles_url, notice: 'Collectible was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collectible
      @collectible = Collectible.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collectible_params
      params.require(:collectible).permit(:name, :description, :collection_id)
    end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collectibles_helper.rb
module CollectiblesHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collectibles/_form.html.erb
<%= form_with(model: collectible, local: true) do |form| %>
  <% if collectible.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collectible.errors.count, "error") %> prohibited this collectible from being saved:</h2>

      <ul>
      <% collectible.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :collection_id %>
    <%= form.select :collection_id, Collection.all.collect {|c| [ c.name, c.id ] }, { include_blank: true }%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/collectibles/edit.html.erb
<h1>Editing Collectible</h1>

<%= render 'form', collectible: @collectible %>

<%= link_to 'Show', @collectible %> |
<%= link_to 'Back', collectibles_path %>

app/views/collectibles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Collectibles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Collection</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collectibles.each do |collectible| %>
      <tr>
        <td><%= collectible.name %></td>
        <td><%= collectible.description %></td>
        <td><%= collectible.collection.name %></td>
        <td><%= link_to 'Show', collectible %></td>
        <td><%= link_to 'Edit', edit_collectible_path(collectible) %></td>
        <td><%= link_to 'Destroy', collectible, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collectible', new_collectible_path %>
<%= link_to 'New Collection', new_collection_path %>

<br>

<%= link_to 'View Collections', collections_path %>

app/views/collectibles/new.html.erb
<h1>New Collectible</h1>

<%= render 'form', collectible: @collectible %>

<%= link_to 'Back', collectibles_path %>

app/views/collectibles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @collectible.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @collectible.description %>
</p>

<p>
  <strong>Collection:</strong>
  <%= @collectible.collection %>
</p>

<%= link_to 'Edit', edit_collectible_path(@collectible) %> |
<%= link_to 'Back', collectibles_path %>

app/views/collections/_form.html.erb
<%= form_with(model: collection, local: true) do |form| %>
  <% if collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Collections</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.name %></td>
        <td><%= link_to 'Show', collection %></td>
        <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
        <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collection', new_collection_path %>
<%= link_to 'Add Collectible', new_collectible_path %>
<br>
<%= link_to 'View Collectibles', collectibles_path %>

app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form', collection: @collection %>


<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

<p>
  <strong>Items:</strong>
  <ul>
    <% @collection.collectibles.each do |c| %>
		<li><%= c.name %></li>
	<% end %>
  </ul>
  <%=  %>
</p>

<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FullStackChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>